package com.example.model;

public enum OrderStatus {
    CREATED,
    PAYMENT_PENDING,
    PAID,
    PAYMENT_FAILED,
    FAILURE_INSUFFICIENT_FUNDS,
    FAILURE_ACCOUNT_NOT_FOUND,
    FAILURE_ORDER_ALREADY_PROCESSED
}